### ISSUE TITLE
configuration problems

### ISSUE THREAD

**Issue by DariusKing** [Klnsyf-Sun/Battle-Royale#2]
hi, at this moment I am trying to configure your plugin in a spigot 1.12 server, the plugin responds well and does not give errors, but when I tried to configure it I had some doubts, about how to configure the maximum number and minimum number of players in a map or world

check your blog and the guide you put on the configuration, i don't read or speak Chinese but  i use google translate, to translate your post to English to make the configuration and the truth is easy to understand how you did the configuration, and the commands, and translated the configuration plugin to English and Spanish locally, but I have this question about how to configure the game options, how many players, the type of terrain, if there were kits, I would appreciate it if you could help me, I hope you are well and that you can update soon your plugin, it's a very good and promising job!

pd: / br does not work, because the server confuses it with the command / br sphere of world edit

**Comment by Klnsyf-Sun** [comment]
So sorry, I'm not good at English, so some of the English expressions may be biased...
// ↑ Praise of `Google Translate`.
In fact, currently there are **NO** configuration about modifying the minimum or maximum number of players in this plugin, but due to the parameters of random transmission, the maximum number of available birth locations generated is limited. For safety consideration, this maximum is designed to be the maximum number of players in a battlefield.
Of course, it's a good idea to add functions as setting the minimum or maximum number of players when presetting a battlefield in subsequent updates.
About the command /br conflict with WordEdit, /b-r or /b_r may be used instead.
Thanks for your issues, and it will be updated soon.

**Comment by DariusKing** [comment]
Thanks for answering, believe me your English is better than mine and I live next to use, before closing this ticket, you just want to have one last thing, this royal battle plugin, on which game is it based? I ask you this question because I am aware that there is a big cultural and social gap between our countries, and I have no idea what can be the game on which you rely for the plugin, here in america we associate battle royale with PUBG or Fornite(maybe this games be called with another name on china xD), possibly in your country, there could be another different games with different game modes, which we know from this side of the world, as a good note it would be good if you gave a brief introduction about the plugin in which you will indicate this information so that people who find your repository is not going to get confused.

**Comment by Klnsyf-Sun** [comment]
In fact, this was an inspiration of mine when WorldBorder appeared in Minecraft 1.8. I tried to port Battle Royale to Minecraft, from the original Minecraft single command-block command to a Java plugin This project has been refactored many times. Of course, because of theirs same origin, this plugin is bound to have the same features as its class, like PUBG. And, in this process some features in this plugin are also modeled on the similar games.
In addition, I will soon add a doc on how to use it, although I do not know why I still have not written yet ... *sighs*
